2025-09-01 01:29:12,409:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:14,307:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:14,307:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:15,287:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:15,287:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:17,071:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
2025-09-01 01:29:17,071:grpc._server:ERROR: Exception iterating responses: 'NoneType' object has no attribute 'x'
Traceback (most recent call last):
  File "/home/jesper/py_fun/snake_sim/snake_venv/lib/python3.12/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesper/py_fun/snake_sim/snake_sim/server/remote_snake_server.py", line 57, in Update
    yield remote_snake_pb2.UpdateResponse(direction=remote_snake_pb2.Coord(x=direction.x, y=direction.y))
                                                                             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
